name: Frontend - Build & Push to ECR
on:
    push:
        branches: ['main']

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install deps
              run: npm ci

            # 프론트는 상대 경로(/api)로 호출할 것이므로 기본값을 /api로 빌드에 주입
            - name: Build
              env:
                  VITE_API_BASE_URL: /api
              run: npm run build

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Login to Amazon ECR
              id: ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build & Push image
              env:
                  REGISTRY: ${{ steps.ecr.outputs.registry }}
              run: |
                  set -e
                  APP=today-stock/frontend
                  SHA=$(git rev-parse --short HEAD)
                  IMAGE_SHA=$REGISTRY/$APP:$SHA
                  IMAGE_LATEST=$REGISTRY/$APP:latest

                  docker buildx build \
                    -t "$IMAGE_SHA" -t "$IMAGE_LATEST" \
                    --push .
